name: recaudo_11
description: "A new Flutter project."
# Prevents the package from being accidentally published to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.4.2
  cupertino_icons: ^1.0.6
  convert: 3.1.1
  permission_handler: ^11.3.0
  http: ^1.2.1
  intl: ^0.19.0
  android_intent: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
